// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tax.Infrastructure.Data;

#nullable disable

namespace Tax.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209145944_14040916init")]
    partial class _14040916init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tax.Domain.Entities.InvoiceBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Am")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bsrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Exr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Mu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Odr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Odt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Olr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Olt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sstid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sstt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Vra")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceHeaderId");

                    b.ToTable("InvoiceBody", (string)null);
                });

            modelBuilder.Entity("Tax.Domain.Entities.InvoiceHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bbc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bccode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bcocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Billid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bpc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bpn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Btel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cdcd")
                        .HasColumnType("int");

                    b.Property<string>("Cdcn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Crn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Did")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Exr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Ft")
                        .HasColumnType("int");

                    b.Property<long?>("Indati2m")
                        .HasColumnType("bigint");

                    b.Property<long?>("Indatim")
                        .HasColumnType("bigint");

                    b.Property<string>("Inno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Inp")
                        .HasColumnType("int");

                    b.Property<int?>("Ins")
                        .HasColumnType("int");

                    b.Property<int?>("Inty")
                        .HasColumnType("int");

                    b.Property<string>("Irtaxid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lrno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Refdt")
                        .HasColumnType("bigint");

                    b.Property<string>("Refno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sbc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sccode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scln")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Setm")
                        .HasColumnType("int");

                    b.Property<string>("Sn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taxid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tob")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tonw")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceHeader", (string)null);
                });

            modelBuilder.Entity("Tax.Domain.Entities.InvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iinn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Pcn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Pdt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pmt")
                        .HasColumnType("int");

                    b.Property<string>("Trmn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceHeaderId");

                    b.ToTable("InvoicePayment", (string)null);
                });

            modelBuilder.Entity("Tax.Domain.Entities.InvoiceBody", b =>
                {
                    b.HasOne("Tax.Domain.Entities.InvoiceHeader", "InvoiceHeader")
                        .WithMany("InvoiceBody")
                        .HasForeignKey("InvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceHeader");
                });

            modelBuilder.Entity("Tax.Domain.Entities.InvoicePayment", b =>
                {
                    b.HasOne("Tax.Domain.Entities.InvoiceHeader", "InvoiceHeader")
                        .WithMany("InvoicePayment")
                        .HasForeignKey("InvoiceHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceHeader");
                });

            modelBuilder.Entity("Tax.Domain.Entities.InvoiceHeader", b =>
                {
                    b.Navigation("InvoiceBody");

                    b.Navigation("InvoicePayment");
                });
#pragma warning restore 612, 618
        }
    }
}
